spring:
  rabbitmq:
    addresses: 120.78.132.139:5672
    username: admin
    password: 1234
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://120.78.132.139:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8001
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.sxw.springbootproducer
  mapper-locations: classpath*:/mappers/*.xml
logging:
  level:
    tk:
      mybatis: trace
